.TH "header Directory Reference" 3 "Tue Apr 27 2021" "Version 1.1" "Bibliotheque virtuelle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
header Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBchoisir\&.h\fP"
.br
.ti -1c
.RI "file \fBconnexion\&.h\fP"
.br
.ti -1c
.RI "file \fBcreatedb\&.h\fP"
.br
.ti -1c
.RI "file \fBdeposer\&.h\fP"
.br
.ti -1c
.RI "file \fBemprunter\&.h\fP"
.br
.ti -1c
.RI "file \fBlister\&.h\fP"
.br
.ti -1c
.RI "file \fBlogin\&.h\fP"
.br
.ti -1c
.RI "file \fBpopulate\&.h\fP"
.br
.in -1c
