.TH "header/choisir.h" 3 "Tue Apr 27 2021" "Version 1.1" "Bibliotheque virtuelle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
header/choisir.h
.SH SYNOPSIS
.br
.PP
\fC#include <mysql/mysql\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBchoisir\fP (MYSQL *con, \fBchar\fP choix[50])"
.br
.RI "Fonction de reinitialisationde la base de donnees\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "choisir (MYSQL * con, \fBchar\fP choix[50])"

.PP
Fonction de reinitialisationde la base de donnees\&. 
.PP
\fBParameters\fP
.RS 4
\fI*con\fP de type MYSQL\&. 
.br
\fIchoix\fP de type char\&. Le bookin choisi
.RE
.PP
Dans Cette fonction, nous enregistrons le choix de l'utilisateur (empruntur) 
.PP
Definition at line 16 of file choisir\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bibliotheque virtuelle from the source code\&.
