.TH "cmake-build-debug/CMakeCache.txt" 3 "Tue Apr 27 2021" "Version 1.1" "Bibliotheque virtuelle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmake-build-debug/CMakeCache.txt
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__has_include\fP (STR)"
.br
.ti -1c
.RI "\fB__has_include__\fP (STR)"
.br
.ti -1c
.RI "\fB__has_include_next\fP (STR)"
.br
.ti -1c
.RI "\fB__has_include_next__\fP (STR)"
.br
.ti -1c
.RI "\fB__INTMAX_C\fP (\fBc\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "CMAKE_ADDR2LINE \fB__pad0__\fP"
.br
.ti -1c
.RI "\fB__STDC_VERSION__\fP"
.br
.ti -1c
.RI "\fB__STDC_UTF_16__\fP"
.br
.ti -1c
.RI "\fB__STDC_UTF_32__\fP"
.br
.ti -1c
.RI "\fB__STDC_HOSTED__\fP"
.br
.ti -1c
.RI "\fB__GNUC__\fP"
.br
.ti -1c
.RI "\fB__GNUC_MINOR__\fP"
.br
.ti -1c
.RI "\fB__GNUC_PATCHLEVEL__\fP"
.br
.ti -1c
.RI "\fB__VERSION__\fP"
.br
.ti -1c
.RI "\fB__ATOMIC_RELAXED\fP"
.br
.ti -1c
.RI "\fB__ATOMIC_SEQ_CST\fP"
.br
.ti -1c
.RI "\fB__ATOMIC_ACQUIRE\fP"
.br
.ti -1c
.RI "\fB__ATOMIC_RELEASE\fP"
.br
.ti -1c
.RI "\fB__ATOMIC_ACQ_REL\fP"
.br
.ti -1c
.RI "\fB__ATOMIC_CONSUME\fP"
.br
.ti -1c
.RI "\fB__pic__\fP"
.br
.ti -1c
.RI "\fB__PIC__\fP"
.br
.ti -1c
.RI "\fB__pie__\fP"
.br
.ti -1c
.RI "\fB__PIE__\fP"
.br
.ti -1c
.RI "\fB__FINITE_MATH_ONLY__\fP"
.br
.ti -1c
.RI "\fB_LP64\fP"
.br
.ti -1c
.RI "\fB__LP64__\fP"
.br
.ti -1c
.RI "\fB__SIZEOF_INT__\fP"
.br
.ti -1c
.RI "\fB__SIZEOF_LONG__\fP"
.br
.ti -1c
.RI "\fB__SIZEOF_LONG_LONG__\fP"
.br
.ti -1c
.RI "\fB__SIZEOF_SHORT__\fP"
.br
.ti -1c
.RI "\fB__SIZEOF_FLOAT__\fP"
.br
.ti -1c
.RI "\fB__SIZEOF_DOUBLE__\fP"
.br
.ti -1c
.RI "\fB__SIZEOF_LONG_DOUBLE__\fP"
.br
.ti -1c
.RI "\fB__SIZEOF_SIZE_T__\fP"
.br
.ti -1c
.RI "\fB__CHAR_BIT__\fP"
.br
.ti -1c
.RI "\fB__BIGGEST_ALIGNMENT__\fP"
.br
.ti -1c
.RI "\fB__ORDER_LITTLE_ENDIAN__\fP"
.br
.ti -1c
.RI "\fB__ORDER_BIG_ENDIAN__\fP"
.br
.ti -1c
.RI "\fB__ORDER_PDP_ENDIAN__\fP"
.br
.ti -1c
.RI "\fB__BYTE_ORDER__\fP"
.br
.ti -1c
.RI "\fB__FLOAT_WORD_ORDER__\fP"
.br
.ti -1c
.RI "\fB__SIZEOF_POINTER__\fP"
.br
.ti -1c
.RI "\fB__SIZE_TYPE__\fP"
.br
.ti -1c
.RI "long unsigned \fBint\fP"
.br
.ti -1c
.RI "\fB__PTRDIFF_TYPE__\fP"
.br
.ti -1c
.RI "\fB__WCHAR_TYPE__\fP"
.br
.ti -1c
.RI "\fB__WINT_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INTMAX_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINTMAX_TYPE__\fP"
.br
.ti -1c
.RI "\fB__CHAR16_TYPE__\fP"
.br
.ti -1c
.RI "\fB__CHAR32_TYPE__\fP"
.br
.ti -1c
.RI "\fB__SIG_ATOMIC_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INT8_TYPE__\fP"
.br
.ti -1c
.RI "signed \fBchar\fP"
.br
.ti -1c
.RI "\fB__INT16_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INT32_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INT64_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT8_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT16_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT32_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT64_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INT_LEAST8_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INT_LEAST16_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INT_LEAST32_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INT_LEAST64_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT_LEAST8_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT_LEAST16_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT_LEAST32_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT_LEAST64_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INT_FAST8_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INT_FAST16_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INT_FAST32_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INT_FAST64_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT_FAST8_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT_FAST16_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT_FAST32_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINT_FAST64_TYPE__\fP"
.br
.ti -1c
.RI "\fB__INTPTR_TYPE__\fP"
.br
.ti -1c
.RI "\fB__UINTPTR_TYPE__\fP"
.br
.ti -1c
.RI "\fB__GXX_ABI_VERSION\fP"
.br
.ti -1c
.RI "\fB__SCHAR_MAX__\fP"
.br
.ti -1c
.RI "\fB__SHRT_MAX__\fP"
.br
.ti -1c
.RI "\fB__INT_MAX__\fP"
.br
.ti -1c
.RI "\fB__LONG_MAX__\fP"
.br
.ti -1c
.RI "\fB__LONG_LONG_MAX__\fP"
.br
.ti -1c
.RI "\fB__WCHAR_MAX__\fP"
.br
.ti -1c
.RI "\fB__WCHAR_MIN__\fP"
.br
.ti -1c
.RI "\fB__WINT_MAX__\fP"
.br
.ti -1c
.RI "\fB__WINT_MIN__\fP"
.br
.ti -1c
.RI "\fB__PTRDIFF_MAX__\fP"
.br
.ti -1c
.RI "\fB__SIZE_MAX__\fP"
.br
.ti -1c
.RI "\fB__SCHAR_WIDTH__\fP"
.br
.ti -1c
.RI "\fB__SHRT_WIDTH__\fP"
.br
.ti -1c
.RI "\fB__INT_WIDTH__\fP"
.br
.ti -1c
.RI "\fB__LONG_WIDTH__\fP"
.br
.ti -1c
.RI "\fB__LONG_LONG_WIDTH__\fP"
.br
.ti -1c
.RI "\fB__WCHAR_WIDTH__\fP"
.br
.ti -1c
.RI "\fB__WINT_WIDTH__\fP"
.br
.ti -1c
.RI "\fB__PTRDIFF_WIDTH__\fP"
.br
.ti -1c
.RI "\fB__SIZE_WIDTH__\fP"
.br
.ti -1c
.RI "\fB__INTMAX_MAX__\fP"
.br
.ti -1c
.RI "\fBc\fP \fBCMAKE_EXTRA_GENERATOR_CXX_SYSTEM_INCLUDE_DIRS\fP"
.br
.ti -1c
.RI "usr \fBinclude\fP x86_64 linux \fBgnu\fP \fBc\fP"
.br
.ti -1c
.RI "usr \fBinclude\fP \fBc\fP \fBbackward\fP"
.br
.ti -1c
.RI "usr lib gcc x86_64 linux \fBgnu\fP \fBinclude\fP"
.br
.ti -1c
.RI "usr \fBinclude\fP x86_64 linux \fBgnu\fP"
.br
.ti -1c
.RI "usr \fBinclude\fP \fBCMAKE_EXTRA_GENERATOR_C_SYSTEM_DEFINED_MACROS\fP"
.br
.ti -1c
.RI "\fBc\fP \fBCMAKE_EXTRA_GENERATOR_C_SYSTEM_INCLUDE_DIRS\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "__has_include (STR)"

.SS "__has_include__ (STR)"

.SS "__has_include_next (STR)"

.SS "__has_include_next__ (STR)"

.SS "__INTMAX_C (\fBc\fP)"

.SH "Variable Documentation"
.PP 
.SS "__ATOMIC_ACQ_REL"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__ATOMIC_ACQUIRE"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__ATOMIC_CONSUME"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__ATOMIC_RELAXED"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__ATOMIC_RELEASE"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__ATOMIC_SEQ_CST"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__BIGGEST_ALIGNMENT__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__BYTE_ORDER__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__CHAR16_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__CHAR32_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__CHAR_BIT__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__FINITE_MATH_ONLY__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__FLOAT_WORD_ORDER__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__GNUC__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__GNUC_MINOR__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__GNUC_PATCHLEVEL__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__GXX_ABI_VERSION"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT16_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT32_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT64_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT8_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT_FAST16_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT_FAST32_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT_FAST64_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT_FAST8_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT_LEAST16_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT_LEAST32_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT_LEAST64_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT_LEAST8_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT_MAX__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INT_WIDTH__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INTMAX_MAX__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INTMAX_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__INTPTR_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__LONG_LONG_MAX__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__LONG_LONG_WIDTH__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__LONG_MAX__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__LONG_WIDTH__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__LP64__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__ORDER_BIG_ENDIAN__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__ORDER_LITTLE_ENDIAN__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__ORDER_PDP_ENDIAN__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "CMAKE_ADDR2LINE __pad0__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__PIC__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__pic__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__pie__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__PIE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__PTRDIFF_MAX__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__PTRDIFF_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__PTRDIFF_WIDTH__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SCHAR_MAX__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SCHAR_WIDTH__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SHRT_MAX__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SHRT_WIDTH__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIG_ATOMIC_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZE_MAX__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZE_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZE_WIDTH__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZEOF_DOUBLE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZEOF_FLOAT__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZEOF_INT__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZEOF_LONG__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZEOF_LONG_DOUBLE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZEOF_LONG_LONG__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZEOF_POINTER__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZEOF_SHORT__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__SIZEOF_SIZE_T__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__STDC_HOSTED__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__STDC_UTF_16__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__STDC_UTF_32__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__STDC_VERSION__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT16_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT32_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT64_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT8_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT_FAST16_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT_FAST32_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT_FAST64_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT_FAST8_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT_LEAST16_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT_LEAST32_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT_LEAST64_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINT_LEAST8_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINTMAX_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__UINTPTR_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__VERSION__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__WCHAR_MAX__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__WCHAR_MIN__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__WCHAR_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__WCHAR_WIDTH__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__WINT_MAX__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__WINT_MIN__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__WINT_TYPE__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "__WINT_WIDTH__"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "_LP64"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "usr \fBinclude\fP \fBc\fP backward"

.PP
Definition at line 325 of file CMakeCache\&.txt\&.
.SS "usr \fBinclude\fP x86_64 linux \fBgnu\fP c"

.PP
Definition at line 325 of file CMakeCache\&.txt\&.
.SS "unsigned char"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SS "usr \fBinclude\fP CMAKE_EXTRA_GENERATOR_C_SYSTEM_DEFINED_MACROS"

.PP
Definition at line 327 of file CMakeCache\&.txt\&.
.SS "\fBc\fP CMAKE_EXTRA_GENERATOR_C_SYSTEM_INCLUDE_DIRS"

.PP
Definition at line 329 of file CMakeCache\&.txt\&.
.SS "\fBc\fP CMAKE_EXTRA_GENERATOR_CXX_SYSTEM_INCLUDE_DIRS"

.PP
Definition at line 325 of file CMakeCache\&.txt\&.
.SS "usr \fBinclude\fP x86_64 linux gnu"

.PP
Definition at line 325 of file CMakeCache\&.txt\&.
.SS "usr local include"

.PP
Definition at line 325 of file CMakeCache\&.txt\&.
.SS "long unsigned int"

.PP
Definition at line 323 of file CMakeCache\&.txt\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bibliotheque virtuelle from the source code\&.
