.TH "header/connexion.h" 3 "Tue Apr 27 2021" "Version 1.1" "Bibliotheque virtuelle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
header/connexion.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <mysql/mysql\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconnexion\fP (MYSQL *con, \fBchar\fP username[50], \fBchar\fP user_password[50], \fBchar\fP dbname[50])"
.br
.RI "Fonction de connexion a la base de donnees\&. "
.ti -1c
.RI "void \fBsavelogin\fP (MYSQL *con, \fBchar\fP student[50])"
.br
.RI "Fonction de reinitialisationde la base de donnees\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "connexion (MYSQL * con, \fBchar\fP username[50], \fBchar\fP user_password[50], \fBchar\fP dbname[50])"

.PP
Fonction de connexion a la base de donnees\&. Dans Cette fonction, nous etablissons une connexion a la bd\&.
.PP
\fBParameters\fP
.RS 4
\fI*con\fP de type MYSQL\&. 
.br
\fIusername\fP de type char\&. Nom d'utilisateur mysal; souvent \fCroot\fP 
.br
\fIuser_password\fP de type char\&. Mot de passe 
.br
\fIdbname\fP de type char\&. Nom de la bd
.RE
.PP
Dans Cette fonction, nous etablissons une connexion a la bd\&. 
.PP
Definition at line 18 of file connexion\&.c\&.
.SS "savelogin (MYSQL * con, \fBchar\fP student[50])"

.PP
Fonction de reinitialisationde la base de donnees\&. Dans Cette fonction, nous tentons une connexion a un compte utilisateur dans l'appli
.PP
\fBParameters\fP
.RS 4
\fI*con\fP de type MYSQL\&. 
.br
\fIstudent\fP de type char\&. Le login avec lequel se connecter
.RE
.PP
Dans Cette fonction, nous tentons une connexion a un compte utilisateur dans l'appli 
.PP
Definition at line 33 of file connexion\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bibliotheque virtuelle from the source code\&.
