.TH "source/lister.c" 3 "Tue Apr 27 2021" "Version 1.1" "Bibliotheque virtuelle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/lister.c \- Fichier lister contenant la fonction lister\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <mysql/mysql\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include '\&.\&./header/lister\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBlister\fP (MYSQL *con)"
.br
.RI "Fonction de creation de la base de donnees\&. "
.in -1c
.SH "Detailed Description"
.PP 
Fichier lister contenant la fonction lister\&. 


.PP
Definition in file \fBlister\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void lister (MYSQL * con)"

.PP
Fonction de creation de la base de donnees\&. Dans Cette fonction, nous faison juste une requete sql et affichons le resultat 
.PP
\fBReturns\fP
.RS 4
On renvoie idx
.RE
.PP
\fBParameters\fP
.RS 4
\fI*con\fP de type MYSQL\&.
.RE
.PP
Dans Cette fonction, nous faison juste une requete sql et affichons le resultat 
.PP
\fBReturns\fP
.RS 4
On renvoie idx 
.RE
.PP

.PP
Definition at line 18 of file lister\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bibliotheque virtuelle from the source code\&.
