.TH "main.c" 3 "Tue Apr 27 2021" "Version 1.1" "Bibliotheque virtuelle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c \- Fichier main est le fichier principale, la racine \&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <mysql/mysql\&.h>\fP
.br
\fC#include '\&./header/populate\&.h'\fP
.br
\fC#include '\&./header/createdb\&.h'\fP
.br
\fC#include '\&./header/connexion\&.h'\fP
.br
\fC#include 'lire\&.c'\fP
.br
\fC#include '\&./header/lister\&.h'\fP
.br
\fC#include '\&./header/login\&.h'\fP
.br
\fC#include '\&./header/choisir\&.h'\fP
.br
\fC#include '\&./header/emprunter\&.h'\fP
.br
\fC#include '\&./header/deposer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmain\fP ()"
.br
.RI "M A I N\&. "
.in -1c
.SH "Detailed Description"
.PP 
Fichier main est le fichier principale, la racine \&. 


.PP
\fBAuthor\fP
.RS 4
Created by mesabo 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate\fP
.RS 4
16/04/2021 
.RE
.PP

.PP
Definition in file \fBmain\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "main ()"

.PP
M A I N\&. fonction mere, tout part d'ici, la fonction principale du projet 
.PP
\fBAttention\fP
.RS 4
certain mot doivent etre utilise sans mofification car ils ont leur place\&.\&.\&. 
.RE
.PP
\fBTodo\fP
.RS 4
permettre la recherche de bookin 
.RE
.PP
INCLUSION DES FONCTIONS
.PP
MENU
.PP
ALTERNATIVE DE CHOIX
.PP
SE CONNECTER AVEC UN LOGIN OU S'ENREGISTRER, LE CAS ECHEANT
.PP
LISTER LES LIVRES DISPONIBLES
.PP
EMPRUNTER UN LIVRE
.PP
DEPOSER UN LIVRE
.PP
Definition at line 28 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bibliotheque virtuelle from the source code\&.
