.TH "source/populate.c" 3 "Tue Apr 27 2021" "Version 1.1" "Bibliotheque virtuelle" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/populate.c \- Fichier populate contenant la fonction add_data\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <mysql/mysql\&.h>\fP
.br
\fC#include '\&.\&./header/populate\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBadd_data\fP (MYSQL *con)"
.br
.RI "Fonction de remplissage de la base de donnees\&. "
.in -1c
.SH "Detailed Description"
.PP 
Fichier populate contenant la fonction add_data\&. 


.PP
Definition in file \fBpopulate\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void add_data (MYSQL * con)"

.PP
Fonction de remplissage de la base de donnees\&. CREATION DES TABLES A NOUVEAU
.PP
REMPLISSAGE DE LA BIBLIOTHEQUE DE LIVRES
.PP
Definition at line 15 of file populate\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Bibliotheque virtuelle from the source code\&.
